name: synth-tools
version: 1.0.0
build-type: Simple
license: BSD3
cabal-version: >= 1.10

-- Trampoline binary for tests and standalone functionality.

-- It seems better to build one binary that can dispatch to an ad-hoc
-- collection of tests and examples based on its first argument,
-- compared to having a collection of distinct binaries.

executable synth-tools
    build-depends: base, Stream, data-reify, containers, data-fix, mtl, lens,
                   process, binary, bytestring, split, QuickCheck,
                   pretty-simple, pure-fft, directory, command

    main-is: synth-tools.hs
    default-language: Haskell2010
    ghc-options: -fprint-potential-instances
    other-modules: SynthTools.DSL
                   SynthTools.Lib
                   SynthTools.Filter
                   SynthTools.IO
                   SynthTools.Eval
                   SynthTools.Num
                   SynthTools.Comp
                   SynthTools.ToC
                   SynthTools.RunC
                   SynthTools.ToV
                   SynthTools.FFT
                   SynthTools.Dataflow
                   SynthTools.CProc
                   SynthTools.Misc
                   SynthTools.TestCproc

