name: synth-tools
version: 1.0.0
build-type: Simple
license: BSD3
cabal-version: >= 1.10

-- This is for the DSL and support code.

-- The finite-fields package didn't compile out of the box.  I don't
-- want to mess with it.

executable synth-tools
    build-depends: base, Stream, data-reify, containers, data-fix, mtl, lens,
                   process, binary, bytestring, split, QuickCheck

 -- finite-fields
    main-is: synth-tools.hs
    default-language: Haskell2010
    ghc-options: -fprint-potential-instances
    other-modules: SynthTools.DSL
                   SynthTools.Lib
                   SynthTools.Filter
                   SynthTools.IO
                   SynthTools.Eval
                   SynthTools.Num
                   SynthTools.Comp
                   SynthTools.ToC
                   SynthTools.RunC
                   SynthTools.ToV
                   SynthTools.NTT

-- This is for the growing the higher level combinators used in the
-- headphones project.

-- base, language-lua, mtl, containers, lens, text
executable test-cproc
    build-depends: base, Stream, data-reify, containers, data-fix, mtl, lens,
                   process, binary, bytestring, directory, split, pretty-simple,
                   QuickCheck, command
    main-is: test-cproc.hs
    default-language: Haskell2010
    ghc-options: -fprint-potential-instances
    other-modules: SynthTools.CProc
                   SynthTools.RunC
                   SynthTools.Dataflow
                   SynthTools.IO
