// generated by epid_cproc.erl
#define CPROC_NB_INPUTS 1
#include "mod_cproc_plugin.c"
void cproc_update(w *input, w g) {
    PROC_COND(g&0b1, n1, edge, NULL, NULL, .in = input[0]);
    PROC_COND(g&0b1, n2, acc, NULL, NULL, .in = n1.out);
    PROC_COND(g&0b1, n3, acc, NULL, NULL, .in = n2.out);
    cproc_output(3, n3.out);
}
