#include "cproc.h"
#include "macros.h"

// system infrastructure
static inline void cproc_output(uint32_t index, w value) {
    LOG("output %d %d\n", index, value);
}

// edge and acc are defined by DEF_PROC in cproc.h

// generated by epid_cproc.erl
#define CPROC_NB_INPUTS 1
void cproc_update(w *input, w g) {
    PROC_COND(g&0b1, n1, edge, NULL, NULL, .in = input[0]);
    PROC_COND(g&0b1, n2, acc,  NULL, NULL, .in = n1.out);
    cproc_output(2, n2.out);
}

// TODO: combinators


int main(int argc, char **argb) {
    LOG("test_cproc.c\n");
    return 0;
}
