#include "cproc.h"
#include "macros.h"

// system infrastructure
static inline void cproc_output(uint32_t index, w value) {
    LOG("output %d %d\n", index, value);
}

// edge and acc are defined by DEF_PROC in cproc.h

// generated by epid_cproc.erl
#define CPROC_NB_INPUTS 1
void cproc_update_1(w *input, w g) {
    PROC_COND(g&0b1, n1, edge, NULL, NULL, .in = input[0]);
    PROC_COND(g&0b1, n2, acc,  NULL, NULL, .in = n1.out);
    cproc_output(2, n2.out);
}

// For manual testing I'm not using PROC_COND, which is for async
// systems.

__attribute__((__noinline__))
void cproc_update(w *input, w g) {
    PROC(e1, edge, NULL, NULL, .in = input[0]);
    PROC(a1, acc,  NULL, NULL, .in = e1.out);
    cproc_output(2, a1.out);
}


// TODO: combinators


int main(int argc, char **argb) {
    LOG("test_cproc.c\n");
    w in[1];
    for (int i=0; i<5; i++) {
        in[0] = 1; cproc_update(in,1);
        in[0] = 0; cproc_update(in,1);
    }
    return 0;
}
