#include "cproc.h"
#include "macros.h"

// system infrastructure
static inline void cproc_output(uint32_t index, w value) {
    LOG("output %d %d\n", index, value);
}

// edge and acc are defined by DEF_PROC in cproc.h

// generated by epid_cproc.erl
#define CPROC_NB_INPUTS 1
void cproc_update_1(w *input, w g) {
    PROC_COND(g&0b1, n1, edge, NULL, NULL, .in = input[0]);
    PROC_COND(g&0b1, n2, acc,  NULL, NULL, .in = n1.out);
    cproc_output(2, n2.out);
}

// For manual testing I'm not using PROC_COND, which is for async
// systems.

__attribute__((__noinline__))
void cproc_update(w *input, w g) {
    PROC(e1, edge, NULL, NULL, .in = input[0]);
    PROC(a1, acc,  NULL, NULL, .in = e1.out);
    cproc_output(2, a1.out);
}

#if 0
// Note that PROC() uses static variables for state, so it won't work
// for creating nested with parameterized state.  To re-use the code
// to create the state struct, it needs to be expressed as a macro so
// that it can be instantiated as a function and a state constructor.
// This does run into issues with introduced names that should be
// replaced at the reference end as well.  Maybe this whole idea of
// embedding it in C is not great...
#define myproc(proc, w *input, w g)         \
    m(e1, edge, NULL, NULL, .in = input[0]) \
    m(a1, acc,  NULL, NULL, .in = e1.out)   \

#endif



// TODO: combinators


int main(int argc, char **argb) {
    LOG("test_cproc.c\n");
    w in[1];
    for (int i=0; i<5; i++) {
        in[0] = 1; cproc_update(in,1);
        in[0] = 0; cproc_update(in,1);
    }
    return 0;
}
